CREATE TABLE IF NOT EXISTS BROWNIE_ORDER (
    ID BIGINT NOT NULL,
    CART BINARY(MAX),
    CUSTOMER_NAME VARCHAR(255),
    TOTAL_PRICE DOUBLE NOT NULL
);

ALTER TABLE BROWNIE_ORDER
MODIFY CART BINARY(MAX);